### ISSUE TITLE
Hello, may I ask if you encountered this issue during installation? Thanks

### ISSUE THREAD

**Issue by zss205** [iangitonga/tinyllama.cpp#1]
gten/ops.h: In function 'void gten::ops::qkv_attn(const gten::Tensor&, const gten::Tensor&, const gten::Tensor&, gten::Tensor&, gten::Tensor&, int, int)':
gten/log.h:7:9: error: '__glibc_unlikely' was not declared in this scope

**Comment by iangitonga** [comment]
Hi, the error is now fixed. I found out the function __glibc_unlikely only works on GCC compilers but it is now removed.You can now compile the source.  I am sure the rest of the code is portable. Feel free to give feedback on how the compilation and execution goes. Thanks.
