### ISSUE TITLE
GTEN ERROR [File `gten/ops.h` line 587]: Assertion 'out_dtype == kQint8 || out_dtype == kFloat32' failed.

### ISSUE THREAD

**Issue by Xuquansheng** [iangitonga/tinyllama.cpp#2]
hello,
I just compiled tinyllama.cpp with your instruction "g++ -std=c++17 -O3 -fopenmp -ffast-math tinyllama.cpp -o tinyllama" on my rocky 8 linux environment, after run ./tinyllama -p "Give three tips for staying healthier.",got an error listed on the title.

**Comment by iangitonga** [comment]
Hi there. The bug has now been fixed. You can now run the model successfully.
