### ISSUE TITLE
Hello, thanks for the timely response, but I have several problems during running

### ISSUE THREAD

**Issue by zss205** [iangitonga/tinyllama.cpp#4]
1. When running fp16, the output will be garbled and will not be output normally.
2. When running int4 and int8, the output result cannot be stopped normally.

**Comment by iangitonga** [comment]
What system are you using? Operating system, CPU, etc.
I ran the [colab notebook](https://colab.research.google.com/drive/1LtYwSimzkO3pxz5lHGrurKf1NoedeXVo) and it seems fine.

**Comment by zss205** [comment]
I use the MACBOOK-intel CPU

**Comment by iangitonga** [comment]
Ok. I found a bug in the tokenizer and I'm currently fixing it.

**Comment by iangitonga** [comment]
The issue with the output text not stopping is now fixed. Also, I hope issue of text being garbled is resolved. Ensure you do not use -ffast-math option. Check the new flags in README file.
